Module1/address
Marin-Andres/talent-standard-tasks pull request #5
Opened 2024-12-11 04:41 UTC by Marin-Andres

2024-12-15 09:36 UTC, kestermvp commented on App/Talent.App.WebApp/wwwroot/js/react/ReactScripts/Profile/Location.jsx
> +            console.log("error",error);
Please remove this one

2024-12-15 09:40 UTC, kestermvp reviewed
Aside from my code feedback, can you please also check why after I updated my details and when I reload the page, the address data will display empty. But after I updated it and reload the page. the content will then show.

2024-12-15 09:40 UTC, kestermvp requested changes
Please check my notes and feedback

2024-12-16 02:27 UTC, Marin-Andres commented
I'm now refreshing the profile data after an update, I think this is now fixed

2024-12-19 20:53 UTC, merged